using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SimpleWMI
{
    class Msft
    {
        public const string WMI_GenericNonCOMEvent = "MSFT_WMI_GenericNonCOMEvent";
        public const string NCProvEvent = "MSFT_NCProvEvent";
        public const string NCProvCancelQuery = "MSFT_NCProvCancelQuery";
        public const string NCProvClientConnected = "MSFT_NCProvClientConnected";
        public const string NCProvNewQuery = "MSFT_NCProvNewQuery";
        public const string NCProvAccessCheck = "MSFT_NCProvAccessCheck";
        public const string SCMEvent = "MSFT_SCMEvent";
        public const string SCMEventLogEvent = "MSFT_SCMEventLogEvent";
        public const string NetSevereServiceFailed = "MSFT_NetSevereServiceFailed";
        public const string NetTransactInvalid = "MSFT_NetTransactInvalid";
        public const string NetServiceNotInteractive = "MSFT_NetServiceNotInteractive";
        public const string NetTakeOwnership = "MSFT_NetTakeOwnership";
        public const string NetServiceConfigBackoutFailed = "MSFT_NetServiceConfigBackoutFailed";
        public const string NetServiceShutdownFailed = "MSFT_NetServiceShutdownFailed";
        public const string NetServiceStartHung = "MSFT_NetServiceStartHung";
        public const string NetServiceStopControlSuccess = "MSFT_NetServiceStopControlSuccess";
        public const string NetServiceSlowStartup = "MSFT_NetServiceSlowStartup";
        public const string NetCallToFunctionFailed = "MSFT_NetCallToFunctionFailed";
        public const string NetBadAccount = "MSFT_NetBadAccount";
        public const string NetBadServiceState = "MSFT_NetBadServiceState";
        public const string NetConnectionTimeout = "MSFT_NetConnectionTimeout";
        public const string NetCircularDependencyAuto = "MSFT_NetCircularDependencyAuto";
        public const string NetServiceStartTypeChanged = "MSFT_NetServiceStartTypeChanged";
        public const string NetServiceLogonTypeNotGranted = "MSFT_NetServiceLogonTypeNotGranted";
        public const string NetServiceStartFailedGroup = "MSFT_NetServiceStartFailedGroup";
        public const string NetDependOnLaterService = "MSFT_NetDependOnLaterService";
        public const string NetFirstLogonFailedII = "MSFT_NetFirstLogonFailedII";
        public const string NetServiceDifferentPIDConnected = "MSFT_NetServiceDifferentPIDConnected";
        public const string NetServiceCrashNoAction = "MSFT_NetServiceCrashNoAction";
        public const string NetCircularDependencyDemand = "MSFT_NetCircularDependencyDemand";
        public const string NetServiceExitFailed = "MSFT_NetServiceExitFailed";
        public const string NetServiceStartFailedII = "MSFT_NetServiceStartFailedII";
        public const string NetServiceExitFailedSpecific = "MSFT_NetServiceExitFailedSpecific";
        public const string NetBootSystemDriversFailed = "MSFT_NetBootSystemDriversFailed";
        public const string NetServiceCrash = "MSFT_NetServiceCrash";
        public const string NetServiceRecoveryFailed = "MSFT_NetServiceRecoveryFailed";
        public const string NetServiceStatusSuccess = "MSFT_NetServiceStatusSuccess";
        public const string NetTransactTimeout = "MSFT_NetTransactTimeout";
        public const string NetFirstLogonFailed = "MSFT_NetFirstLogonFailed";
        public const string NetServiceControlSuccess = "MSFT_NetServiceControlSuccess";
        public const string NetServiceStartFailed = "MSFT_NetServiceStartFailed";
        public const string NetServiceStartFailedNone = "MSFT_NetServiceStartFailedNone";
        public const string NetReadfileTimeout = "MSFT_NetReadfileTimeout";
        public const string NetRevertedToLastKnownGood = "MSFT_NetRevertedToLastKnownGood";
        public const string NetCallToFunctionFailedII = "MSFT_NetCallToFunctionFailedII";
        public const string NetDependOnLaterGroup = "MSFT_NetDependOnLaterGroup";
        public const string WmiSelfEvent = "MSFT_WmiSelfEvent";
        public const string WmiEssEvent = "MSFT_WmiEssEvent";
        public const string WmiThreadPoolEvent = "MSFT_WmiThreadPoolEvent";
        public const string WmiThreadPoolThreadCreated = "MSFT_WmiThreadPoolThreadCreated";
        public const string WmiThreadPoolThreadDeleted = "MSFT_WmiThreadPoolThreadDeleted";
        public const string WmiRegisterNotificationSink = "MSFT_WmiRegisterNotificationSink";
        public const string WmiFilterEvent = "MSFT_WmiFilterEvent";
        public const string WmiFilterDeactivated = "MSFT_WmiFilterDeactivated";
        public const string WmiFilterActivated = "MSFT_WmiFilterActivated";
        public const string WmiCancelNotificationSink = "MSFT_WmiCancelNotificationSink";
        public const string WmiProviderEvent = "MSFT_WmiProviderEvent";
        public const string WmiConsumerProviderEvent = "MSFT_WmiConsumerProviderEvent";
        public const string WmiConsumerProviderSinkLoaded = "MSFT_WmiConsumerProviderSinkLoaded";
        public const string WmiConsumerProviderSinkUnloaded = "MSFT_WmiConsumerProviderSinkUnloaded";
        public const string WmiConsumerProviderUnloaded = "MSFT_WmiConsumerProviderUnloaded";
        public const string WmiConsumerProviderLoaded = "MSFT_WmiConsumerProviderLoaded";
        public const string WmiProvider_OperationEvent = "Msft_WmiProvider_OperationEvent";
        public const string WmiProvider_ComServerLoadOperationEvent = "Msft_WmiProvider_ComServerLoadOperationEvent";
        public const string WmiProvider_OperationEvent_Post = "Msft_WmiProvider_OperationEvent_Post";
        public const string WmiProvider_PutInstanceAsyncEvent_Post = "Msft_WmiProvider_PutInstanceAsyncEvent_Post";
        public const string WmiProvider_CreateInstanceEnumAsyncEvent_Post = "Msft_WmiProvider_CreateInstanceEnumAsyncEvent_Post";
        public const string WmiProvider_DeleteInstanceAsyncEvent_Post = "Msft_WmiProvider_DeleteInstanceAsyncEvent_Post";
        public const string WmiProvider_CancelQuery_Post = "Msft_WmiProvider_CancelQuery_Post";
        public const string WmiProvider_NewQuery_Post = "Msft_WmiProvider_NewQuery_Post";
        public const string WmiProvider_ProvideEvents_Post = "Msft_WmiProvider_ProvideEvents_Post";
        public const string WmiProvider_ExecQueryAsyncEvent_Post = "Msft_WmiProvider_ExecQueryAsyncEvent_Post";
        public const string WmiProvider_AccessCheck_Post = "Msft_WmiProvider_AccessCheck_Post";
        public const string WmiProvider_CreateClassEnumAsyncEvent_Post = "Msft_WmiProvider_CreateClassEnumAsyncEvent_Post";
        public const string WmiProvider_DeleteClassAsyncEvent_Post = "Msft_WmiProvider_DeleteClassAsyncEvent_Post";
        public const string WmiProvider_ExecMethodAsyncEvent_Post = "Msft_WmiProvider_ExecMethodAsyncEvent_Post";
        public const string WmiProvider_GetObjectAsyncEvent_Post = "Msft_WmiProvider_GetObjectAsyncEvent_Post";
        public const string WmiProvider_PutClassAsyncEvent_Post = "Msft_WmiProvider_PutClassAsyncEvent_Post";
        public const string WmiProvider_InitializationOperationFailureEvent = "Msft_WmiProvider_InitializationOperationFailureEvent";
        public const string WmiProvider_InitializationOperationEvent = "Msft_WmiProvider_InitializationOperationEvent";
        public const string WmiProvider_LoadOperationFailureEvent = "Msft_WmiProvider_LoadOperationFailureEvent";
        public const string WmiProvider_ComServerLoadOperationFailureEvent = "Msft_WmiProvider_ComServerLoadOperationFailureEvent";
        public const string WmiProvider_UnLoadOperationEvent = "Msft_WmiProvider_UnLoadOperationEvent";
        public const string WmiProvider_LoadOperationEvent = "Msft_WmiProvider_LoadOperationEvent";
        public const string WmiProvider_OperationEvent_Pre = "Msft_WmiProvider_OperationEvent_Pre";
        public const string WmiProvider_DeleteInstanceAsyncEvent_Pre = "Msft_WmiProvider_DeleteInstanceAsyncEvent_Pre";
        public const string WmiProvider_AccessCheck_Pre = "Msft_WmiProvider_AccessCheck_Pre";
        public const string WmiProvider_ExecQueryAsyncEvent_Pre = "Msft_WmiProvider_ExecQueryAsyncEvent_Pre";
        public const string WmiProvider_DeleteClassAsyncEvent_Pre = "Msft_WmiProvider_DeleteClassAsyncEvent_Pre";
        public const string WmiProvider_NewQuery_Pre = "Msft_WmiProvider_NewQuery_Pre";
        public const string WmiProvider_PutInstanceAsyncEvent_Pre = "Msft_WmiProvider_PutInstanceAsyncEvent_Pre";
        public const string WmiProvider_CreateClassEnumAsyncEvent_Pre = "Msft_WmiProvider_CreateClassEnumAsyncEvent_Pre";
        public const string WmiProvider_ExecMethodAsyncEvent_Pre = "Msft_WmiProvider_ExecMethodAsyncEvent_Pre";
        public const string WmiProvider_ProvideEvents_Pre = "Msft_WmiProvider_ProvideEvents_Pre";
        public const string WmiProvider_CancelQuery_Pre = "Msft_WmiProvider_CancelQuery_Pre";
        public const string WmiProvider_PutClassAsyncEvent_Pre = "Msft_WmiProvider_PutClassAsyncEvent_Pre";
        public const string WmiProvider_GetObjectAsyncEvent_Pre = "Msft_WmiProvider_GetObjectAsyncEvent_Pre";
        public const string WmiProvider_CreateInstanceEnumAsyncEvent_Pre = "Msft_WmiProvider_CreateInstanceEnumAsyncEvent_Pre";
        public const string WmiError = "MSFT_WmiError";
        public const string ExtendedStatus = "MSFT_ExtendedStatus";
        public const string Providers = "Msft_Providers";
        public const string WmiProvider_Counters = "Msft_WmiProvider_Counters";

    }
}
